### PR TITLE
Fix how ARangeNode calculates sizeinfo.min / .max

### LINKED ISSUE #409: Incorrect `sizeinfo.min` and `sizeinfo.max` of `ARangeNode`?
I have been working on a fix for #390 and believe I found a bug in how ARangeNode calculates its `sizeinfo.min` and `sizeinfo.max`?

Given the test code:
```cpp
#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_all.hpp>

#include "dwave-optimization/nodes/creation.hpp"
#include "dwave-optimization/nodes/numbers.hpp"
#include "dwave-optimization/nodes/testing.hpp"

using Catch::Matchers::RangeEquals;

namespace dwave::optimization {

TEST_CASE("ARangeNode") {
    GIVEN("step in {3, 14}, arange = ARangeNode(0, 15, step)") {
        // arange(0, 15, 3) => [0, 3, 6, 9, 12]
        // arange(0, 15, 14) => [0, 14]

        auto graph = Graph();
        auto step_ptr = graph.emplace_node<IntegerNode>(std::initializer_list<ssize_t>{}, 3, 14);

        auto arange_ptr = graph.emplace_node<ARangeNode>(0, 15, step_ptr);
        CHECK(arange_ptr->sizeinfo() == SizeInfo(arange_ptr, 2, 5));
    }
}
}  // namespace dwave::optimization
```
the tests error as follows
```
../tests/cpp/nodes/test_creation.cpp:376: FAILED:
  CHECK( arange_ptr->sizeinfo() == SizeInfo(arange_ptr, 2, 5) )
with expansion:
  <Array at 0xad8c580c0>.size() [min=1 max=5]
  ==
  <Array at 0xad8c580c0>.size() [min=2 max=5]
```
the `sizeinfo.min` for the `ARangeNode` is set to 1 not (my expected) 2? 

I am checking the code now but figured I would post in-case someone sees the mistake I am making

### PR DESCRIPTION
**Pull request by fastbodin**
Close #409

### CODE REVIEW

File: dwave/optimization/src/nodes/creation.cpp [hunk 1]
```diff
@@ -346,16 +346,31 @@ SizeInfo ARangeNode::sizeinfo() const {
...
+    // yeilds the values a, a+s, a+2s, ..., a+ks where k is the largest
+    // integer value such that a+ks < b => k < (b-a)/s. There are two cases.
+    // 1) If s does NOT divide (b-a), then k = floor((b-a)/s)
+    // 2) If s divides (b-a), then k = (b-a)/s - 1
+    //
+    // For such a value k, arange(a, b, s) has k+1 values. Therefore,
+    // 1) If s does NOT divide (b-a), then k+1 = floor((b-a)/s)+1 = ceil((b-a)/s)
+    // 2) If s divides (b-a), then k+1 = (b-a)/s-1+1 = (b-a)/s = ceil((b-a)/s)
+    //
+    // Therefore, arange(a, b, s) defines ceil((b-a)/s) many values
```
Comment (fastbodin) [inline dwave/optimization/src/nodes/creation.cpp]: This explains the correct way to calculate the `sizeinfo.min` and `sizeinfo.max`
